services:
  caddy:
    image: caddy:2.10.0-alpine
    ports:
      - 80:80 # Default port for http
      - 443:443 # Default port for https
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - docker-mern
    depends_on:
      - api
      - frontend