services:
  api:
    image: yairyakobson/mern-auth:backend
    build:
      context: ../backend
      target: development
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - docker-mern
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo