services:
  frontend:
    image: yairyakobson/mern-auth:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
      args:
        VITE_API_URL: https://api.auth.localhost
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - docker-mern
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api