services:
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - docker-mern
    environment:
      - CHOKIDAR_USEPOLLING=true # Windows exclusive
    depends_on:
      - api